sudo: required
services: 
    - docker
env:
    global:
        - SHA=$(git rev-parse HEAD)
        - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
    - curl https://sdk.cloud.google.com | bash > /dev/null;
    - source $HOME/google-cloud-sdk/path.bash.inc
    # - gcloud components update kubectl
    # - gcloud auth activate-service-account --key-file service-account.json
    # - gcloud config set project <projectId>
    # - gcloud config computer/zone <zone>
    # - gcloud container clusters get-credentials <clusterName>
    - docker build -t pawelkonczalski/react-test -f ./client/Dockerfile.dev ./client
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
script:
    - docker run -e CI=true pawelkonczalski/react-test npm test
deploy:
    provider: script
    script: bash ./deploy.sh
    on:
        branch: master